/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as UsarAppRouteImport } from './routes/usar-app'
import { Route as AppAutomatizacionesRouteImport } from './routes/_app/automatizaciones'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppConfiguracionRouteImport } from './routes/_app/configuracion'
import { Route as AppEventosRouteImport } from './routes/_app/eventos'
import { Route as AppHistorialRouteImport } from './routes/_app/historial'
import { Route as AppMemoriaRouteImport } from './routes/_app/memoria'
import { Route as AppPanelRouteImport } from './routes/_app/panel'
import { Route as AppRecordatoriosRouteImport } from './routes/_app/recordatorios'
import { Route as AppTareasRouteImport } from './routes/_app/tareas'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActividadRouteImport } from './routes/admin/actividad'
import { Route as AdminAplicacionRouteImport } from './routes/admin/aplicacion'
import { Route as AdminAutomatizacionesRouteImport } from './routes/admin/automatizaciones'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'
import { Route as AdminIntegracionesRouteImport } from './routes/admin/integraciones'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as ApiApkRouteImport } from './routes/api/apk'
import { Route as ApiDiloRouteImport } from './routes/api/dilo'
import { Route as ApiDispositivoRouteImport } from './routes/api/dispositivo'
import { Route as ApiEjecutarRouteImport } from './routes/api/ejecutar'
import { Route as ApiEstadoRouteImport } from './routes/api/estado'
import { Route as ApiHablarRouteImport } from './routes/api/hablar'
import { Route as ApiInterpretarRouteImport } from './routes/api/interpretar'
import { Route as ApiTranscribirRouteImport } from './routes/api/transcribir'
import { Route as ApiUsuariosRouteImport } from './routes/api/usuarios'
import { Route as ApiWhatsappRouteImport } from './routes/api/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const UsarAppRoute = UsarAppRouteImport.update({
  id: '/usar-app',
  path: '/usar-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutomatizacionesRoute = AppAutomatizacionesRouteImport.update({
  id: '/automatizaciones',
  path: '/automatizaciones',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistorialRoute = AppHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMemoriaRoute = AppMemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPanelRoute = AppPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecordatoriosRoute = AppRecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTareasRoute = AppTareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActividadRoute = AdminActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAplicacionRoute = AdminAplicacionRouteImport.update({
  id: '/aplicacion',
  path: '/aplicacion',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAutomatizacionesRoute = AdminAutomatizacionesRouteImport.update({
  id: '/automatizaciones',
  path: '/automatizaciones',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntegracionesRoute = AdminIntegracionesRouteImport.update({
  id: '/integraciones',
  path: '/integraciones',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiApkRoute = ApiApkRouteImport.update({
  id: '/api/apk',
  path: '/api/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiloRoute = ApiDiloRouteImport.update({
  id: '/api/dilo',
  path: '/api/dilo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDispositivoRoute = ApiDispositivoRouteImport.update({
  id: '/api/dispositivo',
  path: '/api/dispositivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEjecutarRoute = ApiEjecutarRouteImport.update({
  id: '/api/ejecutar',
  path: '/api/ejecutar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEstadoRoute = ApiEstadoRouteImport.update({
  id: '/api/estado',
  path: '/api/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHablarRoute = ApiHablarRouteImport.update({
  id: '/api/hablar',
  path: '/api/hablar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterpretarRoute = ApiInterpretarRouteImport.update({
  id: '/api/interpretar',
  path: '/api/interpretar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribirRoute = ApiTranscribirRouteImport.update({
  id: '/api/transcribir',
  path: '/api/transcribir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsuariosRoute = ApiUsuariosRouteImport.update({
  id: '/api/usuarios',
  path: '/api/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRoute = ApiWhatsappRouteImport.update({
  id: '/api/whatsapp',
  path: '/api/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/usar-app': typeof UsarAppRoute
  '/automatizaciones': typeof AppAutomatizacionesRoute
  '/chat': typeof AppChatRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/eventos': typeof AppEventosRoute
  '/historial': typeof AppHistorialRoute
  '/memoria': typeof AppMemoriaRoute
  '/panel': typeof AppPanelRoute
  '/recordatorios': typeof AppRecordatoriosRoute
  '/tareas': typeof AppTareasRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/aplicacion': typeof AdminAplicacionRoute
  '/admin/automatizaciones': typeof AdminAutomatizacionesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/integraciones': typeof AdminIntegracionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/apk': typeof ApiApkRoute
  '/api/dilo': typeof ApiDiloRoute
  '/api/dispositivo': typeof ApiDispositivoRoute
  '/api/ejecutar': typeof ApiEjecutarRoute
  '/api/estado': typeof ApiEstadoRoute
  '/api/hablar': typeof ApiHablarRoute
  '/api/interpretar': typeof ApiInterpretarRoute
  '/api/transcribir': typeof ApiTranscribirRoute
  '/api/usuarios': typeof ApiUsuariosRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/usar-app': typeof UsarAppRoute
  '/automatizaciones': typeof AppAutomatizacionesRoute
  '/chat': typeof AppChatRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/eventos': typeof AppEventosRoute
  '/historial': typeof AppHistorialRoute
  '/memoria': typeof AppMemoriaRoute
  '/panel': typeof AppPanelRoute
  '/recordatorios': typeof AppRecordatoriosRoute
  '/tareas': typeof AppTareasRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/aplicacion': typeof AdminAplicacionRoute
  '/admin/automatizaciones': typeof AdminAutomatizacionesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/integraciones': typeof AdminIntegracionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/apk': typeof ApiApkRoute
  '/api/dilo': typeof ApiDiloRoute
  '/api/dispositivo': typeof ApiDispositivoRoute
  '/api/ejecutar': typeof ApiEjecutarRoute
  '/api/estado': typeof ApiEstadoRoute
  '/api/hablar': typeof ApiHablarRoute
  '/api/interpretar': typeof ApiInterpretarRoute
  '/api/transcribir': typeof ApiTranscribirRoute
  '/api/usuarios': typeof ApiUsuariosRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registro': typeof RegistroRoute
  '/usar-app': typeof UsarAppRoute
  '/_app/automatizaciones': typeof AppAutomatizacionesRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/eventos': typeof AppEventosRoute
  '/_app/historial': typeof AppHistorialRoute
  '/_app/memoria': typeof AppMemoriaRoute
  '/_app/panel': typeof AppPanelRoute
  '/_app/recordatorios': typeof AppRecordatoriosRoute
  '/_app/tareas': typeof AppTareasRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/aplicacion': typeof AdminAplicacionRoute
  '/admin/automatizaciones': typeof AdminAutomatizacionesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/integraciones': typeof AdminIntegracionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/apk': typeof ApiApkRoute
  '/api/dilo': typeof ApiDiloRoute
  '/api/dispositivo': typeof ApiDispositivoRoute
  '/api/ejecutar': typeof ApiEjecutarRoute
  '/api/estado': typeof ApiEstadoRoute
  '/api/hablar': typeof ApiHablarRoute
  '/api/interpretar': typeof ApiInterpretarRoute
  '/api/transcribir': typeof ApiTranscribirRoute
  '/api/usuarios': typeof ApiUsuariosRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/iniciar-sesion'
    | '/registro'
    | '/usar-app'
    | '/automatizaciones'
    | '/chat'
    | '/configuracion'
    | '/eventos'
    | '/historial'
    | '/memoria'
    | '/panel'
    | '/recordatorios'
    | '/tareas'
    | '/admin/actividad'
    | '/admin/aplicacion'
    | '/admin/automatizaciones'
    | '/admin/configuracion'
    | '/admin/integraciones'
    | '/admin/usuarios'
    | '/api/apk'
    | '/api/dilo'
    | '/api/dispositivo'
    | '/api/ejecutar'
    | '/api/estado'
    | '/api/hablar'
    | '/api/interpretar'
    | '/api/transcribir'
    | '/api/usuarios'
    | '/api/whatsapp'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/iniciar-sesion'
    | '/registro'
    | '/usar-app'
    | '/automatizaciones'
    | '/chat'
    | '/configuracion'
    | '/eventos'
    | '/historial'
    | '/memoria'
    | '/panel'
    | '/recordatorios'
    | '/tareas'
    | '/admin/actividad'
    | '/admin/aplicacion'
    | '/admin/automatizaciones'
    | '/admin/configuracion'
    | '/admin/integraciones'
    | '/admin/usuarios'
    | '/api/apk'
    | '/api/dilo'
    | '/api/dispositivo'
    | '/api/ejecutar'
    | '/api/estado'
    | '/api/hablar'
    | '/api/interpretar'
    | '/api/transcribir'
    | '/api/usuarios'
    | '/api/whatsapp'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/iniciar-sesion'
    | '/registro'
    | '/usar-app'
    | '/_app/automatizaciones'
    | '/_app/chat'
    | '/_app/configuracion'
    | '/_app/eventos'
    | '/_app/historial'
    | '/_app/memoria'
    | '/_app/panel'
    | '/_app/recordatorios'
    | '/_app/tareas'
    | '/admin/actividad'
    | '/admin/aplicacion'
    | '/admin/automatizaciones'
    | '/admin/configuracion'
    | '/admin/integraciones'
    | '/admin/usuarios'
    | '/api/apk'
    | '/api/dilo'
    | '/api/dispositivo'
    | '/api/ejecutar'
    | '/api/estado'
    | '/api/hablar'
    | '/api/interpretar'
    | '/api/transcribir'
    | '/api/usuarios'
    | '/api/whatsapp'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  IniciarSesionRoute: typeof IniciarSesionRoute
  RegistroRoute: typeof RegistroRoute
  UsarAppRoute: typeof UsarAppRoute
  ApiApkRoute: typeof ApiApkRoute
  ApiDiloRoute: typeof ApiDiloRoute
  ApiDispositivoRoute: typeof ApiDispositivoRoute
  ApiEjecutarRoute: typeof ApiEjecutarRoute
  ApiEstadoRoute: typeof ApiEstadoRoute
  ApiHablarRoute: typeof ApiHablarRoute
  ApiInterpretarRoute: typeof ApiInterpretarRoute
  ApiTranscribirRoute: typeof ApiTranscribirRoute
  ApiUsuariosRoute: typeof ApiUsuariosRoute
  ApiWhatsappRoute: typeof ApiWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usar-app': {
      id: '/usar-app'
      path: '/usar-app'
      fullPath: '/usar-app'
      preLoaderRoute: typeof UsarAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/automatizaciones': {
      id: '/_app/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/automatizaciones'
      preLoaderRoute: typeof AppAutomatizacionesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/eventos': {
      id: '/_app/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/historial': {
      id: '/_app/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AppHistorialRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/memoria': {
      id: '/_app/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof AppMemoriaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/panel': {
      id: '/_app/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AppPanelRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/recordatorios': {
      id: '/_app/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof AppRecordatoriosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tareas': {
      id: '/_app/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof AppTareasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/actividad': {
      id: '/admin/actividad'
      path: '/actividad'
      fullPath: '/admin/actividad'
      preLoaderRoute: typeof AdminActividadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/aplicacion': {
      id: '/admin/aplicacion'
      path: '/aplicacion'
      fullPath: '/admin/aplicacion'
      preLoaderRoute: typeof AdminAplicacionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/automatizaciones': {
      id: '/admin/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/admin/automatizaciones'
      preLoaderRoute: typeof AdminAutomatizacionesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/integraciones': {
      id: '/admin/integraciones'
      path: '/integraciones'
      fullPath: '/admin/integraciones'
      preLoaderRoute: typeof AdminIntegracionesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/apk': {
      id: '/api/apk'
      path: '/api/apk'
      fullPath: '/api/apk'
      preLoaderRoute: typeof ApiApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dilo': {
      id: '/api/dilo'
      path: '/api/dilo'
      fullPath: '/api/dilo'
      preLoaderRoute: typeof ApiDiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dispositivo': {
      id: '/api/dispositivo'
      path: '/api/dispositivo'
      fullPath: '/api/dispositivo'
      preLoaderRoute: typeof ApiDispositivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ejecutar': {
      id: '/api/ejecutar'
      path: '/api/ejecutar'
      fullPath: '/api/ejecutar'
      preLoaderRoute: typeof ApiEjecutarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/estado': {
      id: '/api/estado'
      path: '/api/estado'
      fullPath: '/api/estado'
      preLoaderRoute: typeof ApiEstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hablar': {
      id: '/api/hablar'
      path: '/api/hablar'
      fullPath: '/api/hablar'
      preLoaderRoute: typeof ApiHablarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interpretar': {
      id: '/api/interpretar'
      path: '/api/interpretar'
      fullPath: '/api/interpretar'
      preLoaderRoute: typeof ApiInterpretarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribir': {
      id: '/api/transcribir'
      path: '/api/transcribir'
      fullPath: '/api/transcribir'
      preLoaderRoute: typeof ApiTranscribirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/usuarios': {
      id: '/api/usuarios'
      path: '/api/usuarios'
      fullPath: '/api/usuarios'
      preLoaderRoute: typeof ApiUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp': {
      id: '/api/whatsapp'
      path: '/api/whatsapp'
      fullPath: '/api/whatsapp'
      preLoaderRoute: typeof ApiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppAutomatizacionesRoute: typeof AppAutomatizacionesRoute
  AppChatRoute: typeof AppChatRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppEventosRoute: typeof AppEventosRoute
  AppHistorialRoute: typeof AppHistorialRoute
  AppMemoriaRoute: typeof AppMemoriaRoute
  AppPanelRoute: typeof AppPanelRoute
  AppRecordatoriosRoute: typeof AppRecordatoriosRoute
  AppTareasRoute: typeof AppTareasRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAutomatizacionesRoute: AppAutomatizacionesRoute,
  AppChatRoute: AppChatRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppEventosRoute: AppEventosRoute,
  AppHistorialRoute: AppHistorialRoute,
  AppMemoriaRoute: AppMemoriaRoute,
  AppPanelRoute: AppPanelRoute,
  AppRecordatoriosRoute: AppRecordatoriosRoute,
  AppTareasRoute: AppTareasRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminActividadRoute: typeof AdminActividadRoute
  AdminAplicacionRoute: typeof AdminAplicacionRoute
  AdminAutomatizacionesRoute: typeof AdminAutomatizacionesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminIntegracionesRoute: typeof AdminIntegracionesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminActividadRoute: AdminActividadRoute,
  AdminAplicacionRoute: AdminAplicacionRoute,
  AdminAutomatizacionesRoute: AdminAutomatizacionesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminIntegracionesRoute: AdminIntegracionesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  IniciarSesionRoute: IniciarSesionRoute,
  RegistroRoute: RegistroRoute,
  UsarAppRoute: UsarAppRoute,
  ApiApkRoute: ApiApkRoute,
  ApiDiloRoute: ApiDiloRoute,
  ApiDispositivoRoute: ApiDispositivoRoute,
  ApiEjecutarRoute: ApiEjecutarRoute,
  ApiEstadoRoute: ApiEstadoRoute,
  ApiHablarRoute: ApiHablarRoute,
  ApiInterpretarRoute: ApiInterpretarRoute,
  ApiTranscribirRoute: ApiTranscribirRoute,
  ApiUsuariosRoute: ApiUsuariosRoute,
  ApiWhatsappRoute: ApiWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
